---
abstract: 'which Unix classic command for Windows'
author:
  - 'Olivier Mengué <dolmen@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.3800
dynamic_config: 0
generated_by: 'Module::Build version 0.4004, CPAN::Meta::Converter version 2.132661'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Win32-App-which
provides:
  Win32::App::which:
    file: lib/Win32/App/which.pm
    version: 1.022
requires:
  perl: 5.008
resources:
  license: http://www.gnu.org/licenses/gpl-3.0.html
  repository: https://github.com/dolmen/p5-Win32-App-which.git
version: 1.022
